const ballList = [
    { "ball": "Master", "number": 0 },
    { "ball": "Ultra", "number": 1 },
    { "ball": "Great", "number": 2 },
    { "ball": "Poke", "number": 3 },
    { "ball": "Safari", "number": 4 },
    { "ball": "Net", "number": 5 },
    { "ball": "Dive", "number": 6 },
    { "ball": "Nest", "number": 7 },
    { "ball": "Repeat", "number": 8 },
    { "ball": "Timer", "number": 9 },
    { "ball": "Luxury", "number": 10 },
    { "ball": "Premier", "number": 11 },
    { "ball": "Dusk", "number": 12 },
    { "ball": "Heal", "number": 13 },
    { "ball": "Quick", "number": 14 },
    { "ball": "Cherish", "number": 15 },
    { "ball": "Fast", "number": 16 },
    { "ball": "Level", "number": 17 },
    { "ball": "Lure", "number": 18 },
    { "ball": "Heavy", "number": 19 },
    { "ball": "Love", "number": 20 },
    { "ball": "Friend", "number": 21 },
    { "ball": "Moon", "number": 22 },
    { "ball": "Sport", "number": 23 },
    { "ball": "Dream", "number": 24 },
    { "ball": "Beast", "number": 25 },
];