const teraList = [
    { "type": "Normal", "number": 0 },
    { "type": "Fighting", "number": 1 },
    { "type": "Flying", "number": 2 },
    { "type": "Poison", "number": 3 },
    { "type": "Ground", "number": 4 },
    { "type": "Rock", "number": 5 },
    { "type": "Bug", "number": 6 },
    { "type": "Ghost", "number": 7 },
    { "type": "Steel", "number": 8 },
    { "type": "Fire", "number": 9 },
    { "type": "Water", "number": 10 },
    { "type": "Grass", "number": 11 },
    { "type": "Electric", "number": 12 },
    { "type": "Psychic", "number": 13 },
    { "type": "Ice", "number": 14 },
    { "type": "Dragon", "number": 15 },
    { "type": "Dark", "number": 16 },
    { "type": "Fairy", "number": 17 },
];